#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER} -v ON_ERROR_STOP=1"

$POSTGRES --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE orders;
EOSQL

$POSTGRES --dbname "orders" <<-EOSQL
    CREATE TABLE USERS(
        ID SERIAL PRIMARY KEY,
        USERNAME VARCHAR NOT NULL,
        PASSWORD VARCHAR NOT NULL
    );
    CREATE TABLE PRODUCTOS(
        IDEN SERIAL PRIMARY KEY,
        NOMBRE VARCHAR NOT NULL,
        DESCRIPCION VARCHAR NOT NULL,
        PRECIOBASE DECIMAL NOT NULL,
        TASAIMPUESTOS DECIMAL NOT NULL,
        ESTADO VARCHAR NOT NULL,
        CANTINVE INT NOT NULL
    );
EOSQL